DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS COMPROBANTE;
DROP TABLE IF EXISTS LINEA;

CREATE TABLE CLIENTES(
IDCLIENTE INT NOT NULL AUTO_INCREMENT,
DNI INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PRODUCTOS(
IDPRODUCTO INT NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(100) NOT NULL,
PRECIO FLOAT NOT NULL,
STOCK INT NOT NULL,
CODIGO VARCHAR(6) NOT NULL,
PRIMARY KEY (IDPRODUCTO)
);

CREATE TABLE COMPROBANTE(
IDCOMPROBANTE INT NOT NULL AUTO_INCREMENT,
IDCLIENTE INT NOT NULL,
CANTIDAD INT NOT NULL,
FECHA DATE,
TOTAL FLOAT NOT NULL,
PRIMARY KEY (IDCOMPROBANTE)
);

CREATE TABLE LINEA(
IDLINEA INT NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(255) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO FLOAT NOT NULL,
IDCOMPROBANTE INT NOT NULL,
IDPRODUCTO INT NOT NULL,
PRIMARY KEY(IDLINEA)
);